# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('last_updated', models.DateField()),
                ('cur_temp', models.IntegerField()),
                ('temp_string', models.TextField()),
                ('time_string', models.TextField()),
                ('threshold', models.IntegerField()),
            ],
        ),
    ]
