# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
