# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTapp', '0004_auto_20161229_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
