# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IOTapp', '0006_devicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
