# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTapp', '0007_auto_20161231_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='user',
        ),
        migrations.AddField(
            model_name='devicelog',
            name='is_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
