# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IOTapp', '0008_auto_20170101_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
